#include <memory>
#include <string>
#include <vector>
#include <map>
#include <vulkan/vulkan.hpp>
#include <vulkan/vulkan.h>
#include <filesystem>
#include "error.h"
#include "potentia-core/base/global_singleton.h"
#include <cstddef>
